---
- import_playbook: playbooks/00-preparePhysicalESXi.yml
- import_playbook: playbooks/01-deployNestedESXi.yml 

- name: Wait 5 more minutes the Nested_Clusters hosts to become fully responsive
  hosts: localhost
  gather_facts: False
  vars_files:
    - ./answerfile.yml
  tasks:
    - name: Wait 5 minutes before start checking wheter the hosts are ready
      pause: minutes=1
- import_playbook:  playbooks/02-connectNestedESXi.yml 
- import_playbook:  playbooks/03-createVDS.yml
- import_playbook:  playbooks/04-createVSS.yml 
#- import_playbook:  playbooks/05-migrateuplinkVDS.yml
