##
##    Project: SDDC-NSXT-LAB
##    Authors: Sachin Kumar Sharma
##   Filename: playbooks/03-createVDS-migrateuplinks.yml
##    Purpose: This Ansbile script is to prepare the nested environment, which includes:
##              a) Creating vSphere Switch
##              b) Creating vSphere Port-Groups and uplink port groups
##              c) VMK for vMotion, vSAN and NFS
##              d) migrating uplinks to VDS
##              e) migrating management vmk0 to VDS
##
---
- name: Create VDS and Management, vMotion, vSAN, NFS portgroup and vmk and migrate vmk0 and vmnics
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: createVds_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"
    - name: Create Distributed Switch for Nested Clusters
      community.vmware.vmware_dvswitch:
        hostname: "{{ vCSA.ip }}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        datacenter_name: "{{ vCSA.datacenter }}"
        validate_certs: false
        switch_name: "{{ item.value.vds_name }}"
        mtu: "{{ physicalESXi.mtu_size }}"
        uplink_quantity: 2
        discovery_proto: lldp
        discovery_operation: both
        state: present
      register: vds
      with_dict: "{{ Nested_Clusters }}"

    - name: Create Management Portgroup for Nested Clusters
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vCSA.ip }}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        switch_name: "{{ item.value.vds_name }}"
        portgroup_name: "{{ item.value.pg_mgmt_name }}"
        vlan_id: "{{ item.value.mgmt_vlan }}"
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
      register: pg
      with_dict: "{{ Nested_Clusters }}"
    - name: Create vMotion Portgroup  for Nested Clusters
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vCSA.ip }}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        switch_name: "{{ item.value.vds_name }}"
        portgroup_name: "{{ item.value.pg_vmotion_name }}"
        vlan_id: "{{ item.value.vmotion_vlan }}"
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
      register: vmotion_pg
      with_dict: "{{ Nested_Clusters }}"
    - name: Create vSAN Portgroup  for  for Nested Clusters
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vCSA.ip }}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        switch_name: "{{ item.value.vds_name }}"
        portgroup_name: "{{ item.value.pg_vsan_name }}"
        vlan_id:  "{{ item.value.vsan_vlan }}"
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
      register: vsan_pg
      with_dict: "{{ Nested_Clusters }}"
    - name: Create NFS Portgroup  for  for Nested Clusters
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vCSA.ip }}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        switch_name: "{{ item.value.vds_name }}"
        portgroup_name: "{{ item.value.pg_nfs_name }}"
        vlan_id:  0
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
      register: nfs_pg
      with_dict: "{{ Nested_Clusters }}"

    - name: Create Uplink1 port group
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vCSA.ip}}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        switch_name: "{{ item.value.vds_name }}"
        portgroup_name: "{{ item.value.pg_uplink1_name }}"
        vlan_trunk: true
        vlan_id: "0-4094"
        num_ports: 8
        portgroup_type: earlyBinding
        state: present
      register: NSXEdgeUplink1_pg
      with_dict: "{{ Nested_Clusters }}"
    - name: Create Uplink2 port group
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vCSA.ip }}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        switch_name: "{{ item.value.vds_name }}"
        portgroup_name: "{{ item.value.pg_uplink1_name }}"
        vlan_trunk: true
        vlan_id: "0-4094"
        num_ports: 8
        portgroup_type: earlyBinding
        state: present
      register: NSXEdgeUplink2_pg
      with_dict: "{{ Nested_Clusters }}"

    - name: Migrate uplinks vmknic1 to the VDS
      community.vmware.vmware_dvs_host:
        hostname: "{{ vCSA.ip}}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.mgmt_hostname }}"
        switch_name: "{{ item.value.vds_name }}"
        vmnics:
          - vmnic1
        state: present
      with_dict: "{{ Nested_Clusters}}"
    - name: Migrate vmk0 to the VDS
      community.vmware.vmware_migrate_vmk:
        hostname: "{{ vCSA.ip}}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.mgmt_hostname }}"
        device: 'vmk0'
        current_switch_name: 'vSwitch0'
        current_portgroup_name: 'Management Network'
        migrate_switch_name: "{{ item.value.vds_name }}"
        migrate_portgroup_name: "{{ item.value.pg_mgmt_name }}"
      with_dict: "{{ Nested_Clusters}}"
    - name: Remove a  vSwitch from the Nested Clusters host to free vmnic0
      community.vmware.vmware_vswitch:
        hostname: "{{ vCSA.ip }}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.mgmt_hostname }}"
        switch_name: "vSwitch0"
        nic_name: vmnic0
        state: absent        
      with_dict: "{{ Nested_Clusters }}"
      register: vmnic0del
    - name: Migrate uplinks vmknic0 to the VDS
      community.vmware.vmware_dvs_host:
        hostname: "{{ vCSA.ip}}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.mgmt_hostname }}"
        switch_name: "{{ item.value.vds_name }}"
        vmnics:
          - vmnic0
          - vmnic1
        state: present
      with_dict: "{{ Nested_Clusters}}"

    - name: Create vmk1 for vMotion
      community.vmware.vmware_vmkernel:
        hostname: "{{ vCSA.ip}}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.mgmt_hostname }}"
        portgroup_name: "{{ item.value.pg_vmotion_name }}"
        dvswitch_name: "{{ item.value.vds_name }}"
        enable_vmotion: true
        mtu: "{{ physicalESXi.mtu_size }}"
        network:
          type: 'static'
          ip_address: "{{ item.value.vmotion_ip }}"
          subnet_mask: "{{ item.value.vmotion_mask }}"
          default_gateway: "{{ item.value.vmotion_gw }}"
          #tcpip_stack: vmotion
        state: present
      register: vmk1_vMotion
      with_dict: "{{ Nested_Clusters }}"
    - name: Create vmk2 for vSAN
      community.vmware.vmware_vmkernel:
        hostname: "{{ vCSA.ip}}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.mgmt_hostname }}"
        portgroup_name: "{{ item.value.pg_vsan_name }}"
        dvswitch_name: "{{ item.value.vds_name }}"
        enable_vsan: true
        mtu: "{{ physicalESXi.mtu_size }}"
        network:
          type: 'static'
          ip_address: "{{ item.value.vsan_ip }}"
          subnet_mask: "{{ item.value.vsan_mask }}"
          default_gateway: "{{ item.value.vsan_gw }}"
        state: present
      register: vmk2_vSAN
      with_dict: "{{ Nested_Clusters }}"
    - name: Create vmk3 for NFS
      community.vmware.vmware_vmkernel:
        hostname: "{{ vCSA.ip}}"
        username: "{{ vCSA.user }}"
        password: "{{ vCSA.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.mgmt_hostname }}"
        portgroup_name: "{{ item.value.pg_nfs_name }}"
        dvswitch_name: "{{ item.value.vds_name }}"
        #mtu: "{{ physicalESXi.mtu_size }}"
        enable_mgmt: True
        device: vmk3
        network:
          type: 'dhcp'
        state: present
      register: vmk3_NFS
      with_dict: "{{ Nested_Clusters }}"