##
##    Project: SDDC-NSXT-LAB
##    Authors: Sachin Kumar Sharma
##    Filename: playbooks/13-configure-nsxtmanager-license.yml
##    Purpose: This Ansbile script is to register NSXT manager licence
##
##
---
- hosts: localhost
  name: Apply license to NSX-T Manager
  gather_facts: false
  vars_files:
   - ../answerfile.yml
   - ../secrets/license

  tasks:
    - name: onfigure-nsxtmanager-licens_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"
    - name: Apply license to NSX-T Manager
      nsxt_licenses:
          hostname: "{{ NSXT.hostname }}"
          username: "{{ NSXT.admin_user }}"
          password: "{{ NSXT.admin_password }}"
          validate_certs: "{{ NSXT.validate_certs }}"
          license_key: "{{ license }}"
          state: "present"
