##
##    Project: SDDC-NSXT-LAB
##    Authors: Sachin Kumar Sharma
##    Filename: playbooks/16-configure-nsxtmanager-transportzones.yml 
##    Purpose: This Ansbile script is to Create NSX-T Transport Zones Overlay & VLAN for COMPUTE and EDGE NODES
##
##
---
- hosts: localhost
  name: Create NSX-T Transport Zones Overlay & VLAN for COMPUTE and EDGE NODES
  gather_facts: false
  vars_files: ../answerfile.yml

  tasks:
    - name: configure-nsxtmanager-transportzone_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"

    - name: Create NSX-T 3.0 transport zone - COMPUTE-CLUSTER
      nsxt_transport_zones:
          hostname: "{{ NSXT.hostname }}"
          username: "{{ NSXT.admin_user }}"
          password: "{{ NSXT.admin_password }}"
          validate_certs: "{{ NSXT.validate_certs }}"
          resource_type: "TransportZone"
          display_name: "{{ NSXT.tz_compute_overlay_name }}"
          description: "Ansible provisionned - Transport Zone - Overlay"
          transport_type: "OVERLAY"
          host_switch_mode: "STANDARD"
          state: "present"



    - name: Create NSX-T 3.0 transport zone - Common COMPUTE VLANs 
      nsxt_transport_zones:
          hostname: "{{ NSXT.hostname }}"
          username: "{{ NSXT.admin_user }}"
          password: "{{ NSXT.admin_password }}"
          validate_certs: "{{ NSXT.validate_certs }}"
          resource_type: "TransportZone"
          display_name: "{{ NSXT.tz_compute_vlan_name }}"
          description: "Ansible provisionned - Transport Zone - Vlan"
          transport_type: "VLAN"
          host_switch_mode: "STANDARD"
          state: "present"


    - name: Create NSX-T 3.0 transport zone - EDGE VLAN 
      nsxt_transport_zones:
          hostname: "{{ NSXT.hostname }}"
          username: "{{ NSXT.admin_user }}"
          password: "{{ NSXT.admin_password }}"
          validate_certs: "{{ NSXT.validate_certs }}"
          resource_type: "TransportZone"
          display_name: "{{ NSXT.tz_edge_vlan_name }}"
          description: "Ansible provisionned - Transport Zone - Vlan"
          transport_type: "VLAN"
          host_switch_mode: "STANDARD"
          uplink_teaming_policy_names: "{{ NSXT.edge_uplink_teaming_policies }}"
          state: "present"
