---
- name: Test play
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Wait until the NSX-T API reports that the NSX-T Manager cluster is "STABLE"
      ansible.builtin.uri:
        url: https://{{ NSXT.fqdn }}/api/v1/cluster/status
        validate_certs: no
        timeout: 5
        force_basic_auth: yes
        url_username: "{{ NSXT.admin_user }}"
        url_password: "{{ NSXT.admin_password }}"
        method: GET
        body_format: json
        return_content: yes
        status_code: 200
      register: result
      until: result.status == 200 and result.json.detailed_cluster_status.overall_status == "STABLE"
      retries: 60
      delay: 60
